# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 503094290d700d1a0ef439688dc49df70a5a9436976c022ce95053782375f607632da262f2ea129483757825d022eaf8341a48c75bc64712eab17fe471cca5b3

test:
  secret_key_base: 3814e53fe78675ffc6c5262ca6b76bce9bee43aaa0f78d099660ec9ee0316cafbdeddb64d5ef67762d00e0560c9947897c66630ee9fe187aa6d7c5caf8824829

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
